version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./:/app
      - ./output:/opt/app/output
    env_file:
      - .env
    depends_on:
      - grid
  grid:
    image: selenium/standalone-chrome:112.0-chromedriver-112.0-grid-4.9.0-20230421
    ports:
      - "4444:4444"
    shm_size: 2gb
    environment:
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=${THREADS}
